"""Initial migration

Revision ID: 5437d78f9fb8
Revises: 
Create Date: 2024-09-14 08:25:43.405981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5437d78f9fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searchkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searchkeys_key'), ['key'], unique=True)

    with op.batch_alter_table('searchkey', schema=None) as batch_op:
        batch_op.drop_index('ix_searchkey_key')

    op.drop_table('searchkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchkey',
    sa.Column('keywordId', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('keywordId')
    )
    with op.batch_alter_table('searchkey', schema=None) as batch_op:
        batch_op.create_index('ix_searchkey_key', ['key'], unique=1)

    with op.batch_alter_table('searchkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searchkeys_key'))

    op.drop_table('searchkeys')
    # ### end Alembic commands ###
